# Generated by Django 4.0.6 on 2022-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
